# Generated by Django 4.1.4 on 2022-12-22 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0002_alter_cartitem_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='total_price',
        ),
    ]
