# Generated by Django 4.1.4 on 2022-12-22 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0003_remove_cartitem_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='total_price',
        ),
    ]
