# Generated by Django 4.1.4 on 2022-12-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0004_remove_orderitem_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=6),
            preserve_default=False,
        ),
    ]
